newIssueWelcomeComment: >
  Thank you for opening an issue! One of our team members will get back to you shortly with additional information.


  If this is a product issue, please close this issue and contact the particular product's support instead. For a list of support websites, see [Support for Microsoft products and apps](https://support.microsoft.com/all-products).